-- MySQL Script generated by MySQL Workbench
-- Fri Mar 10 17:09:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Grafeat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Grafeat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Grafeat` DEFAULT CHARACTER SET utf8 ;
USE `Grafeat` ;

-- -----------------------------------------------------
-- Table `Grafeat`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grafeat`.`tb_categorias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Grafeat`.`tb_vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grafeat`.`tb_vendedor` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `data_de_nascimento` DATE NOT NULL,
  `localidade` VARCHAR(255) NOT NULL,
  `resgatar_saldo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Grafeat`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Grafeat`.`tb_produtos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  `material` VARCHAR(255) NOT NULL,
  `quantidade` VARCHAR(255) NOT NULL,
  `tamanho` VARCHAR(255) NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `tb_categorias_id` BIGINT NULL,
  `tb_vendedor_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_produtos_tb_categorias_idx` (`tb_categorias_id` ASC),
  INDEX `fk_tb_produtos_tb_vendedor1_idx` (`tb_vendedor_id` ASC),
  CONSTRAINT `fk_tb_produtos_tb_categorias`
    FOREIGN KEY (`tb_categorias_id`)
    REFERENCES `Grafeat`.`tb_categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produtos_tb_vendedor1`
    FOREIGN KEY (`tb_vendedor_id`)
    REFERENCES `Grafeat`.`tb_vendedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
